### PR TITLE
problem: upload dir not writable by user

### PR DESCRIPTION
**Pull request by gazhayes**
solution: move upload dir to home directory

### CODE REVIEW

**Comment by gazhayes** [comment]
I'm fixing the tests now.

**Comment by gazhayes** [comment]
OMG finally it passes LOL.

ping @samuelralak

**Comment by samuelralak** [comment]
finally...after all the commits 😂

**Comment by gazhayes** [comment]
Yeah, I spent the first hour to find a missing "/" 

bang-head-on-wall

**Comment by samuelralak** [comment]
it happens to most of us 😂good game of hide and seek

**Pull request merged**
