### PR TITLE
problem: minutes estimate is on new problem page

### PR DESCRIPTION
**Pull request by AshHimself**
solution: remove all estimate elements from problem page and add to the claiming process in a swal modal #231

### CODE REVIEW

**Comment by anbud** [comment]
Restarting the build, Travis is being weird these days.

**Comment by gazhayes** [comment]
```
[34mI20180608-11:59:36.781(0)? [39m[0m  1) problem methods can claim the problem if available:
[34mI20180608-11:59:36.782(0)? [39m[0m[31m     ClientError: Estimate is required[0m[90m
[34mI20180608-11:59:36.782(0)? [39m      at /home/travis/build/EmurgoHK/Emurgis/node_modules/simpl-schema/dist/SimpleSchema.js:637:21
[34mI20180608-11:59:36.782(0)? [39m      at Array.forEach (<anonymous>)
[34mI20180608-11:59:36.783(0)? [39m      at SimpleSchema.validate (/home/travis/build/EmurgoHK/Emurgis/node_modules/simpl-schema/dist/SimpleSchema.js:625:15)
[34mI20180608-11:59:36.783(0)? [39m      at MethodInvocation.<anonymous> (/home/travis/build/EmurgoHK/Emurgis/node_modules/simpl-schema/dist/SimpleSchema.js:672:16)
[34mI20180608-11:59:36.783(0)? [39m      at ValidatedMethod._execute (packages/mdg:validated-method/validated-method.js:86:28)
[34mI20180608-11:59:36.784(0)? [39m      at MethodInvocation.claimProblem (packages/mdg:validated-method/validated-method.js:54:23)
[34mI20180608-11:59:36.784(0)? [39m      at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)
[34mI20180608-11:59:36.784(0)? [39m      at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:1686:15)
[34mI20180608-11:59:36.785(0)? [39m      at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
[34mI20180608-11:59:36.785(0)? [39m      at resolve (packages/ddp-server/livedata_server.js:1684:36)
[34mI20180608-11:59:36.786(0)? [39m      at new Promise (<anonymous>)
[34mI20180608-11:59:36.786(0)? [39m      at Server.applyAsync (packages/ddp-server/livedata_server.js:1683:12)
[34mI20180608-11:59:36.786(0)? [39m      at Server.apply (packages/ddp-server/livedata_server.js:1622:26)
[34mI20180608-11:59:36.787(0)? [39m      at Promise (imports/api/utilities.js:9:16)
[34mI20180608-11:59:36.787(0)? [39m      at new Promise (<anonymous>)
[34mI20180608-11:59:36.788(0)? [39m      at callWithPromise (imports/api/utilities.js:8:12)
[34mI20180608-11:59:36.789(0)? [39m      at Test.it (imports/api/documents/both/problemMethods.test.js:178:16)
[34mI20180608-11:59:36.789(0)? [39m      at run (packages/practicalmeteor:mocha-core/server.js:34:29)
[34mI20180608-11:59:36.790(0)? [39m      at Context.wrappedFunction (packages/practicalmeteor:mocha-core/server.js:63:33)
[34mI20180608-11:59:36.791(0)? [39m[0m
[34mI20180608-11:59:36.792(0)? [39m[0m  2) problem methods cannot claim the problem if already claimed:
[34mI20180608-11:59:36.793(0)? [39m[0m[31m     AssertionError: expected 'Estimate is required' to include 'You cannot claim a problem that is already claimed'[0m[90m
[34mI20180608-11:59:36.793(0)? [39m      at callWithPromise.then.catch.err (imports/api/documents/both/problemMethods.test.js:199:20)
[34mI20180608-11:59:36.794(0)? [39m      at /home/travis/.meteor/packages/promise/.0.10.1.vagou5.w6j8++os+web.browser+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
[34mI20180608-11:59:36.795(0)? [39m[0m
[34mI20180608-11:59:36.796(0)? [39m
[34mI20180608-11:59:36.797(0)? [39m
[34mI20180608-11:59:36.797(0)? [39mLoad the app in a browser to run client tests, or set the TEST_BROWSER_DRIVER environment variable. See https://github.com/meteortesting/meteor-mocha/blob/master/README.md#run-app-tests
```

**Comment by gazhayes** [comment]
ping @AshHimself

**Comment by AshHimself** [comment]
@gazhayes looking

**Comment by anbud** [comment]
@AshHimself, if you're stuck, ping me and I'll fix them. :)

**Comment by gazhayes** [comment]
@AshHimself if you just resolve the conflicts I'll merge this anyway and we can deal with failing tests later

**Comment by AshHimself** [comment]
@gazhayes - I resolved this via github is that all good? I've actually not done it like this before, typically send another PR.

**Comment by gazhayes** [comment]
Yeah its fine

**Pull request merged**
