### PR TITLE
problem: layout isnt very good on small screens

### PR DESCRIPTION
**Pull request by AshHimself**
solution: make Emurgis reactive and offer a better UX on smaller screens #288

### CODE REVIEW

**Comment by anbud** [comment]
@AshHimself, do you want to give it a try and fix the test or should I?

The failing one is in the `header.ui-test.js`, the one that checks if the GitHub link is always visible (which now isn't the case anymore). Basically, I think you can just remove the `.isVisible` check.

**Comment by AshHimself** [comment]
oh dear... I honestly didn't check the test to see if github link was in it..

I am doing another PR for this ticket so will fix at the exact same time. Cheers for bringing it to my attention. 
@anbud - anyway to be notified if these fail or do I just have to come back and check the PR?

**Comment by AshHimself** [comment]
@anbud - unless this is going to break all tests until i've done it, in which case go for it!!!

**Comment by anbud** [comment]
Ok, I'll merge this one then.

I don't think there's a way to be notified, so you can just check after the PR. It takes about 9-10 minutes to complete all tests. But don't worry about it too much, I usually ping when I see failing tests. :)

**Comment by anbud** [comment]
I've fixed it in #291. :)

**Pull request merged**
