### PR TITLE
problem:problem detail page does not show who claimed an issue

### PR DESCRIPTION
**Pull request by AshHimself**
solution: Update var to query profile.name instead of just name. #101

### CODE REVIEW

**Comment by gazhayes** [comment]
@AshHimself failing tests

**Comment by AshHimself** [comment]
Oh dear.. ok let me see what is going on here..

**Comment by gazhayes** [comment]
The other PR too, probably same issue

**Comment by AshHimself** [comment]
What user does our tests run under.. does it have a profile.name field.

**Comment by samuelralak** [comment]
Yeah, the test user should have a profile.name field. I remember adding
that there myself. Seems like that change was overwritten. Check out PR #80

**Pull request merged**
