### PR TITLE
Problem: No mentions tab (#363)

### PR DESCRIPTION
**Pull request by anbud**
Solution: Add a new mentions page where users can see where they've been mentioned. Include the mentions count in the header.

### CODE REVIEW

**Comment by samuelralak** [comment]
@anbud test failure alert

**Comment by anbud** [comment]
I'll check them out later today. 
They're passing locally, I'm not sure why they're failing here. :)

**Comment by anbud** [comment]
It's green now, feel free to merge. 

This one was a little bit difficult to spot, there were actually issues with parallelism, some tests removed data required by other tests that were running simultaneously, but I've managed to fix it.

**Comment by samuelralak** [comment]
awesome 👍

**Pull request merged**
